### PR TITLE
Support of more than one simulation and different improvenets

### PR DESCRIPTION
**Pull request by ra3xdh**
I have recently installed and tried Caneda. The application in general looks good, but I have found a lot of bugs and decided to fix some of them. Here is the summary of the changes that I have made:

### Enabled support for more than one simulation in schematic: 

If schematic contains more that one simulation the variables names are not displayed correctly and the plot may contain garbage data. I have fixed these problems. Caneda should support more than simulation on schematic with my patch. 

* Fixed variable reading when more that simulation presents in RAW output file: https://github.com/ra3xdh/Caneda/commit/94c940f64032394e67f7e351996c72d4ad8680ee
* Fixed incorrect values reading from RAW file with more than one simulation: https://github.com/ra3xdh/Caneda/commit/f87b815db69d8a6c6a8ef1e55721cc3ce9d9678f
* Set the X-axis type (time/frequency) automatically according the first selected waveform. Before it was always taken from the first waveform in the list. https://github.com/ra3xdh/Caneda/commit/16a91142080f9efbbf9913a65a2ebfdf5775ab27 

### Some general improvements
* Create a new symbol file if F3 is pressed and symbol file doesn't exist: https://github.com/ra3xdh/Caneda/commit/ae90d863a499bbd5a9121f0bbfcc62cc25545768
* Fixed crash when new diagram on the simulation window is opened and then closed: https://github.com/ra3xdh/Caneda/commit/fda3d0ee73be23a61774ca7e9ce73e1bd53a8e19
* Activate `-Wall -Wextra` in CMake and fix some warnings https://github.com/ra3xdh/Caneda/commit/cbcfdda76c211e3dd8789fa85150822d4eee2df1
* Generate `.save` directive and print only nodes with explicit names and probes. Otherwise the raw file may become oversized and diagram will contain a lot of redundant traces for large schematics: https://github.com/ra3xdh/Caneda/commit/b74a8a272cb0c7c64c9fc17d3f9a9e13cd153a31

Here is example of schematic with two simulations: AC and TRAN. As you can see, the X-axis varibale name is show correctly for each plot subwindow. 
image
image

### CODE REVIEW

**Comment by ra3xdh** [comment]
I have added the fix of the build error for Qt5.15+Qwt6.3.0 Otherwise it doesn't build on Arch.

**Comment by parejaobregon** [comment]
For some reason, currents seem not to be saved. I need to look into this issue. Anyway, I'll probably open a new issue for that.

**Comment by ra3xdh** [comment]
Yes, it seems I didn't check the schematic containing the current probes. It will require some time for me to remember what I did for this PR, because more than two years has been passed. Probably I will provide a fix, probably you will be sooner.

**Comment by parejaobregon** [comment]
Apparently the save directive includes all nodes in the same way (using the selected probe name). Which, according to ngspice is ok for voltages. In the case of current plots, instead of using:

`.save NAME`

We should be using:

`.save i(VNAME)`

That should do the trick. Granted, the prefix V in the name will not be ideal, but at least the currents will be plotted. I'll try to jog my memory a bit as well, but I guess creating a second list for currents before creating the save commands should do.

**Comment by parejaobregon** [comment]
Fixed in latest commit.

Thanks for your support.

**Pull request merged**
